- name: conditions
  hosts: local
  connection: local
  vars:
    number: 12
  tasks:
  - name: check number is less then 10 or not
    ansible.builtin.debug:
      msg: "Given number {{ number }} is lee then 10"
    when: number < 10
